server:
  port: 7000
spring:
  zipkin:
    base-url: http://localhost:7050
  sleuth:
    sampler:
      percentage: 0.1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1112/eureka/,http://localhost:1113/eureka/

# log trace detail
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG