server:
  port: 3051
spring:
  application:
    name: eureka-consumer-feign-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1112/eureka/,http://localhost:1113/eureka/
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
