server:
  port: 4000
spring:
  application:
    name: eureka-gateway-zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1112/eureka/,http://localhost:1113/eureka/
#zuul:
#  ignored-services: '*'
#  routes:
#    eureka-provider: /user-service/**

#zuul:
#  AccessFilter:
#    pre:
#      disable: true